language: node_js
node_js:
  - "10.11.0"
cache:
  directories:
    - "node_modules"
before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in secrets.js.enc -out config/secrets.js -d
