name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: azure/appservice-actions/webapp@master
      with: 
        app-name: die-lernwerkstatt
        publish-profile: ${{ secrets.azure }}
